language: java
jdk:
  - openjdk8

script:
  - ant

branch: master

deploy:
  provider: releases
  api_key: $GITHUB_RELEASE_TOKEN
  file:
    - dist/image-halftone.jar
    - dist/image-halftone-javadoc.jar
  skip_cleanup: true
  on:
    tags: true
